[2025-03-02T19:07:06.696+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T19:07:06.729+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_entities.extract_and_load_omie_entities.extract_and_load_ListarMovimentos manual__2025-03-02T19:04:38.315016+00:00 [queued]>
[2025-03-02T19:07:06.742+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_entities.extract_and_load_omie_entities.extract_and_load_ListarMovimentos manual__2025-03-02T19:04:38.315016+00:00 [queued]>
[2025-03-02T19:07:06.744+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2025-03-02T19:07:06.764+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_omie_entities.extract_and_load_ListarMovimentos> on 2025-03-02 19:04:38.315016+00:00
[2025-03-02T19:07:06.771+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=177) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-02T19:07:06.773+0000] {standard_task_runner.py:72} INFO - Started process 178 to run task
[2025-03-02T19:07:06.776+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'execute_entities', 'extract_and_load_omie_entities.extract_and_load_ListarMovimentos', 'manual__2025-03-02T19:04:38.315016+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/execute_entities.py', '--cfg-path', '/tmp/tmprqmoaf_7']
[2025-03-02T19:07:06.779+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask extract_and_load_omie_entities.extract_and_load_ListarMovimentos
[2025-03-02T19:07:06.860+0000] {task_command.py:467} INFO - Running <TaskInstance: execute_entities.extract_and_load_omie_entities.extract_and_load_ListarMovimentos manual__2025-03-02T19:04:38.315016+00:00 [running]> on host eba33f90d1de
[2025-03-02T19:07:06.987+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='execute_entities' AIRFLOW_CTX_TASK_ID='extract_and_load_omie_entities.extract_and_load_ListarMovimentos' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T19:04:38.315016+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T19:04:38.315016+00:00'
[2025-03-02T19:07:06.988+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-02T19:07:07.047+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/execute_entities.py", line 22, in get_cutomers
    from src.controllers.paginations import PaginationController
  File "/sources/src/controllers/paginations/__init__.py", line 1, in <module>
    from .paginations import PaginationController
  File "/sources/src/controllers/paginations/paginations.py", line 5, in <module>
    from api import Api
ModuleNotFoundError: No module named 'api'
[2025-03-02T19:07:07.083+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_entities, task_id=extract_and_load_omie_entities.extract_and_load_ListarMovimentos, run_id=manual__2025-03-02T19:04:38.315016+00:00, execution_date=20250302T190438, start_date=20250302T190706, end_date=20250302T190707
[2025-03-02T19:07:07.107+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-02T19:07:07.108+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 58 for task extract_and_load_omie_entities.extract_and_load_ListarMovimentos (No module named 'api'; 178)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/execute_entities.py", line 22, in get_cutomers
    from src.controllers.paginations import PaginationController
  File "/sources/src/controllers/paginations/__init__.py", line 1, in <module>
    from .paginations import PaginationController
  File "/sources/src/controllers/paginations/paginations.py", line 5, in <module>
    from api import Api
ModuleNotFoundError: No module named 'api'
[2025-03-02T19:07:07.152+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-02T19:07:07.187+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T19:07:07.189+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
